version: '2'
services:
  web:
    build: .
    ports:
     - '3000:3000'
    volumes:
     - .:/usr/src/app
    depends_on:
     - mongo
    environment:
     - DB_URL=mongodb://mongo/booksharingapp
    
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: