version: '2'
services:
  web:
    build: .
    ports:
     - '3000:3000'
    links:
     - mongo
    depends_on:
     - mongo
    environment:
     - DB_URL=mongodb://mongo/booksharingapp
  mongo:
    image: 'mongo'
    command: '--smallfiles'
    ports:
      - "27017:27017"
